# --- Defaults --- #

name = "frugal-core-dev"
main = "dist/index.mjs"
compatibility_date = "2023-04-09"
workers_dev = true
# no_bundle = true

[build]
command = "npx turbo build"
watch_dir = "src"

[[rules]]
type = "ESModule"
globs = ["**/*.ts", "**/*.tsx"]

# --- Staging --- #

[env.staging]
name = "frugal-core-stg"

[env.staging.vars]
ENVIRONMENT = "staging"

[[env.staging.durable_objects.bindings]]
name = "GIVEAWAY_STATE"
class_name = "GiveawayState"

[[env.staging.migrations]]
tag = "v1"
new_classes = ["GiveawayState"]

[[env.staging.kv_namespaces]]
binding = "KV"
id = "4a0966b541644a8fb749fb96a4867670"

[[env.staging.r2_buckets]]
binding = "STORAGE"
bucket_name = "frugal-staging"

[[env.staging.analytics_engine_datasets]]
binding = "ANALYTICS"

[env.staging.build]
command = "NODE_ENV=production npx turbo build"

[[env.staging.d1_databases]]
binding = "D1"
database_name = "frugal"
database_id = "25175d02-8239-4f77-b53a-f8edd2fe6ebd"
migrations_dir = "../../packages/d1-database/migrations"

# --- Production --- #

[env.production]
name = "frugal-core-prd"

[env.production.vars]
ENVIRONMENT = "production"

[[env.production.durable_objects.bindings]]
name = "GIVEAWAY_STATE"
class_name = "GiveawayState"

[[env.production.migrations]]
tag = "v1"
new_classes = ["GiveawayState"]

[[env.production.kv_namespaces]]
binding = "KV"
id = "9d21020092f1485badd0d5efdff2352e"

[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "frugal-prod"

[[env.production.analytics_engine_datasets]]
binding = "ANALYTICS"

[env.production.build]
command = "NODE_ENV=production npx turbo build"
watch_dir = "src"

[[env.production.d1_databases]]
binding = "D1"
database_name = "frugal"
database_id = "a09d43b8-850e-4f4d-ba91-fe47d3be0ec9"
migrations_dir = "../../packages/d1-database/migrations"

# --- Development, or unspecified --- #

[vars]
ENVIRONMENT = "development"

[[durable_objects.bindings]]
name = "GIVEAWAY_STATE"
class_name = "GiveawayState"

[[migrations]]
tag = "v1"
new_classes = ["GiveawayState"]

[[kv_namespaces]]
binding = "KV"
id = "ff4da80f1e42471db838c38e8e73a3ed"
preview_id = "ff4da80f1e42471db838c38e8e73a3ed"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "frugal-devel"
preview_bucket_name = "frugal-devel"

[[analytics_engine_datasets]]
binding = "ANALYTICS"

[[d1_databases]]
binding = "D1"
database_name = "frugal"
database_id = "ddc7d747-ada2-4e1c-9946-62856277f9a1"
preview_database_id = "ddc7d747-ada2-4e1c-9946-62856277f9a1"
migrations_dir = "../../packages/d1-database/migrations"