// Generated by Wrangler by running `wrangler types`

interface Env {
	KV_SESSIONS: KVNamespace;
	SESSION_SECRET: string;
	DISCORD_CLIENT_ID: string;
	DISCORD_CLIENT_SECRET: string;
	DISCORD_CALLBACK_URL: string;
	SENTRY_DSN: string;
	STORAGE: R2Bucket;
	D1: D1Database;
}
