[[d1_databases]]
binding = "D1"
database_name = "frugal"
database_id = "ddc7d747-ada2-4e1c-9946-62856277f9a1"
preview_database_id = "ddc7d747-ada2-4e1c-9946-62856277f9a1"
migrations_dir = "../../packages/d1-database/migrations"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "frugal-devel"
preview_bucket_name = "frugal-devel"

[[kv_namespaces]]
binding = "KV_SESSIONS"
id = "dad8c886278d4341aed8926d38747ea4"
preview_id = "dad8c886278d4341aed8926d38747ea4"
