compatibility_date = "2022-10-22"
main = "dist/index.mjs"
name = "frugal-core-dev"
workers_dev = true
no_bundle = true

[[rules]]
type = "ESModule"
globs = ["**/*.ts", "**/*.tsx"]

# --- Staging --- #

[env.staging]
name = "frugal-core-stg"

[env.staging.vars]
ENVIRONMENT = "staging"

[[env.staging.durable_objects.bindings]]
name = "TIMERS"
class_name = "Timer"

[[env.staging.migrations]]
tag = "v1"
new_classes = ["Timer"]

[[env.staging.kv_namespaces]]
binding = "KV"
id = "4a0966b541644a8fb749fb96a4867670"

[[env.staging.r2_buckets]]
binding = "STORAGE"
bucket_name = "frugal-staging"

[[env.staging.analytics_engine_datasets]]
binding = "ANALYTICS"

# --- Production --- #

[env.production]
name = "frugal-core-prd"

[env.production.vars]
ENVIRONMENT = "production"

[[env.production.durable_objects.bindings]]
name = "TIMERS"
class_name = "Timer"

[[env.production.migrations]]
tag = "v1"
new_classes = ["Timer"]

[[env.production.kv_namespaces]]
binding = "KV"
id = "9d21020092f1485badd0d5efdff2352e"

[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "frugal-prod"

[[env.production.analytics_engine_datasets]]
binding = "ANALYTICS"

# --- Development or otherwise --- #

[vars]
ENVIRONMENT = "development"

[[durable_objects.bindings]]
name = "TIMERS"
class_name = "Timer"

[[migrations]]
tag = "v1"
new_classes = ["Timer"]

[[kv_namespaces]]
binding = "KV"
id = "ff4da80f1e42471db838c38e8e73a3ed"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "frugal-devel"

[[analytics_engine_datasets]]
binding = "ANALYTICS"

[build]
command = "node scripts/build.js production"

[env.development.build]
command = "node scripts/build.js development"

[env.development.build.upload] # Required by Miniflare
format = "modules"
main = "./index.mjs"

[miniflare]
env_path = ".dev.vars"
r2_persist = true
d1_persist = true
cache_persist = true
durable_objects_persist = true
global_async_io = true # Required by Slshx
