/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as AddedRouteImport } from './routes/added'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as GiveawaysIndexRouteImport } from './routes/giveaways/index'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalPaidServicesRouteImport } from './routes/legal/paid-services'
import { Route as GiveawaysOverviewRouteImport } from './routes/giveaways/overview'
import { Route as GiveawaysGuildIdRouteImport } from './routes/giveaways/$guildId'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as ApiReportingRouteImport } from './routes/api/reporting'
import { Route as WikiUserGuidesIndexRouteImport } from './routes/wiki/user-guides/index'
import { Route as WikiReferenceIndexRouteImport } from './routes/wiki/reference/index'
import { Route as WikiGettingStartedIndexRouteImport } from './routes/wiki/getting-started/index'
import { Route as WikiDeveloperIndexRouteImport } from './routes/wiki/developer/index'
import { Route as WikiAdvancedIndexRouteImport } from './routes/wiki/advanced/index'
import { Route as GiveawaysSummariesIndexRouteImport } from './routes/giveaways/summaries/index'
import { Route as WikiReferenceCommandsRouteImport } from './routes/wiki/reference/commands'
import { Route as WikiGettingStartedQuickStartRouteImport } from './routes/wiki/getting-started/quick-start'
import { Route as WikiDeveloperMarkdownTestRouteImport } from './routes/wiki/developer/markdown-test'
import { Route as WikiDeveloperComponentsRouteImport } from './routes/wiki/developer/components'
import { Route as GiveawaysSummariesSummaryIdRouteImport } from './routes/giveaways/summaries/$summaryId'
import { Route as GiveawaysDetailsGiveawayIdRouteImport } from './routes/giveaways/details/$giveawayId'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AddedRoute = AddedRouteImport.update({
  id: '/added',
  path: '/added',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WikiRoute,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegalRoute,
} as any)
const GiveawaysIndexRoute = GiveawaysIndexRouteImport.update({
  id: '/giveaways/',
  path: '/giveaways/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPaidServicesRoute = LegalPaidServicesRouteImport.update({
  id: '/paid-services',
  path: '/paid-services',
  getParentRoute: () => LegalRoute,
} as any)
const GiveawaysOverviewRoute = GiveawaysOverviewRouteImport.update({
  id: '/giveaways/overview',
  path: '/giveaways/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveawaysGuildIdRoute = GiveawaysGuildIdRouteImport.update({
  id: '/giveaways/$guildId',
  path: '/giveaways/$guildId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportingRoute = ApiReportingRouteImport.update({
  id: '/api/reporting',
  path: '/api/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiUserGuidesIndexRoute = WikiUserGuidesIndexRouteImport.update({
  id: '/user-guides/',
  path: '/user-guides/',
  getParentRoute: () => WikiRoute,
} as any)
const WikiReferenceIndexRoute = WikiReferenceIndexRouteImport.update({
  id: '/reference/',
  path: '/reference/',
  getParentRoute: () => WikiRoute,
} as any)
const WikiGettingStartedIndexRoute = WikiGettingStartedIndexRouteImport.update({
  id: '/getting-started/',
  path: '/getting-started/',
  getParentRoute: () => WikiRoute,
} as any)
const WikiDeveloperIndexRoute = WikiDeveloperIndexRouteImport.update({
  id: '/developer/',
  path: '/developer/',
  getParentRoute: () => WikiRoute,
} as any)
const WikiAdvancedIndexRoute = WikiAdvancedIndexRouteImport.update({
  id: '/advanced/',
  path: '/advanced/',
  getParentRoute: () => WikiRoute,
} as any)
const GiveawaysSummariesIndexRoute = GiveawaysSummariesIndexRouteImport.update({
  id: '/giveaways/summaries/',
  path: '/giveaways/summaries/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiReferenceCommandsRoute = WikiReferenceCommandsRouteImport.update({
  id: '/reference/commands',
  path: '/reference/commands',
  getParentRoute: () => WikiRoute,
} as any)
const WikiGettingStartedQuickStartRoute =
  WikiGettingStartedQuickStartRouteImport.update({
    id: '/getting-started/quick-start',
    path: '/getting-started/quick-start',
    getParentRoute: () => WikiRoute,
  } as any)
const WikiDeveloperMarkdownTestRoute =
  WikiDeveloperMarkdownTestRouteImport.update({
    id: '/developer/markdown-test',
    path: '/developer/markdown-test',
    getParentRoute: () => WikiRoute,
  } as any)
const WikiDeveloperComponentsRoute = WikiDeveloperComponentsRouteImport.update({
  id: '/developer/components',
  path: '/developer/components',
  getParentRoute: () => WikiRoute,
} as any)
const GiveawaysSummariesSummaryIdRoute =
  GiveawaysSummariesSummaryIdRouteImport.update({
    id: '/giveaways/summaries/$summaryId',
    path: '/giveaways/summaries/$summaryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const GiveawaysDetailsGiveawayIdRoute =
  GiveawaysDetailsGiveawayIdRouteImport.update({
    id: '/giveaways/details/$giveawayId',
    path: '/giveaways/details/$giveawayId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/added': typeof AddedRoute
  '/invite': typeof InviteRoute
  '/legal': typeof LegalRouteWithChildren
  '/premium': typeof PremiumRoute
  '/wiki': typeof WikiRouteWithChildren
  '/api/reporting': typeof ApiReportingRoute
  '/auth/error': typeof AuthErrorRoute
  '/giveaways/$guildId': typeof GiveawaysGuildIdRoute
  '/giveaways/overview': typeof GiveawaysOverviewRoute
  '/legal/paid-services': typeof LegalPaidServicesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/giveaways': typeof GiveawaysIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/giveaways/details/$giveawayId': typeof GiveawaysDetailsGiveawayIdRoute
  '/giveaways/summaries/$summaryId': typeof GiveawaysSummariesSummaryIdRoute
  '/wiki/developer/components': typeof WikiDeveloperComponentsRoute
  '/wiki/developer/markdown-test': typeof WikiDeveloperMarkdownTestRoute
  '/wiki/getting-started/quick-start': typeof WikiGettingStartedQuickStartRoute
  '/wiki/reference/commands': typeof WikiReferenceCommandsRoute
  '/giveaways/summaries': typeof GiveawaysSummariesIndexRoute
  '/wiki/advanced': typeof WikiAdvancedIndexRoute
  '/wiki/developer': typeof WikiDeveloperIndexRoute
  '/wiki/getting-started': typeof WikiGettingStartedIndexRoute
  '/wiki/reference': typeof WikiReferenceIndexRoute
  '/wiki/user-guides': typeof WikiUserGuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/added': typeof AddedRoute
  '/invite': typeof InviteRoute
  '/premium': typeof PremiumRoute
  '/api/reporting': typeof ApiReportingRoute
  '/auth/error': typeof AuthErrorRoute
  '/giveaways/$guildId': typeof GiveawaysGuildIdRoute
  '/giveaways/overview': typeof GiveawaysOverviewRoute
  '/legal/paid-services': typeof LegalPaidServicesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/giveaways': typeof GiveawaysIndexRoute
  '/legal': typeof LegalIndexRoute
  '/wiki': typeof WikiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/giveaways/details/$giveawayId': typeof GiveawaysDetailsGiveawayIdRoute
  '/giveaways/summaries/$summaryId': typeof GiveawaysSummariesSummaryIdRoute
  '/wiki/developer/components': typeof WikiDeveloperComponentsRoute
  '/wiki/developer/markdown-test': typeof WikiDeveloperMarkdownTestRoute
  '/wiki/getting-started/quick-start': typeof WikiGettingStartedQuickStartRoute
  '/wiki/reference/commands': typeof WikiReferenceCommandsRoute
  '/giveaways/summaries': typeof GiveawaysSummariesIndexRoute
  '/wiki/advanced': typeof WikiAdvancedIndexRoute
  '/wiki/developer': typeof WikiDeveloperIndexRoute
  '/wiki/getting-started': typeof WikiGettingStartedIndexRoute
  '/wiki/reference': typeof WikiReferenceIndexRoute
  '/wiki/user-guides': typeof WikiUserGuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/added': typeof AddedRoute
  '/invite': typeof InviteRoute
  '/legal': typeof LegalRouteWithChildren
  '/premium': typeof PremiumRoute
  '/wiki': typeof WikiRouteWithChildren
  '/api/reporting': typeof ApiReportingRoute
  '/auth/error': typeof AuthErrorRoute
  '/giveaways/$guildId': typeof GiveawaysGuildIdRoute
  '/giveaways/overview': typeof GiveawaysOverviewRoute
  '/legal/paid-services': typeof LegalPaidServicesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/giveaways/': typeof GiveawaysIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/giveaways/details/$giveawayId': typeof GiveawaysDetailsGiveawayIdRoute
  '/giveaways/summaries/$summaryId': typeof GiveawaysSummariesSummaryIdRoute
  '/wiki/developer/components': typeof WikiDeveloperComponentsRoute
  '/wiki/developer/markdown-test': typeof WikiDeveloperMarkdownTestRoute
  '/wiki/getting-started/quick-start': typeof WikiGettingStartedQuickStartRoute
  '/wiki/reference/commands': typeof WikiReferenceCommandsRoute
  '/giveaways/summaries/': typeof GiveawaysSummariesIndexRoute
  '/wiki/advanced/': typeof WikiAdvancedIndexRoute
  '/wiki/developer/': typeof WikiDeveloperIndexRoute
  '/wiki/getting-started/': typeof WikiGettingStartedIndexRoute
  '/wiki/reference/': typeof WikiReferenceIndexRoute
  '/wiki/user-guides/': typeof WikiUserGuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/added'
    | '/invite'
    | '/legal'
    | '/premium'
    | '/wiki'
    | '/api/reporting'
    | '/auth/error'
    | '/giveaways/$guildId'
    | '/giveaways/overview'
    | '/legal/paid-services'
    | '/legal/privacy'
    | '/legal/terms'
    | '/giveaways'
    | '/legal/'
    | '/wiki/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/giveaways/details/$giveawayId'
    | '/giveaways/summaries/$summaryId'
    | '/wiki/developer/components'
    | '/wiki/developer/markdown-test'
    | '/wiki/getting-started/quick-start'
    | '/wiki/reference/commands'
    | '/giveaways/summaries'
    | '/wiki/advanced'
    | '/wiki/developer'
    | '/wiki/getting-started'
    | '/wiki/reference'
    | '/wiki/user-guides'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/added'
    | '/invite'
    | '/premium'
    | '/api/reporting'
    | '/auth/error'
    | '/giveaways/$guildId'
    | '/giveaways/overview'
    | '/legal/paid-services'
    | '/legal/privacy'
    | '/legal/terms'
    | '/giveaways'
    | '/legal'
    | '/wiki'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/giveaways/details/$giveawayId'
    | '/giveaways/summaries/$summaryId'
    | '/wiki/developer/components'
    | '/wiki/developer/markdown-test'
    | '/wiki/getting-started/quick-start'
    | '/wiki/reference/commands'
    | '/giveaways/summaries'
    | '/wiki/advanced'
    | '/wiki/developer'
    | '/wiki/getting-started'
    | '/wiki/reference'
    | '/wiki/user-guides'
  id:
    | '__root__'
    | '/'
    | '/added'
    | '/invite'
    | '/legal'
    | '/premium'
    | '/wiki'
    | '/api/reporting'
    | '/auth/error'
    | '/giveaways/$guildId'
    | '/giveaways/overview'
    | '/legal/paid-services'
    | '/legal/privacy'
    | '/legal/terms'
    | '/giveaways/'
    | '/legal/'
    | '/wiki/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/giveaways/details/$giveawayId'
    | '/giveaways/summaries/$summaryId'
    | '/wiki/developer/components'
    | '/wiki/developer/markdown-test'
    | '/wiki/getting-started/quick-start'
    | '/wiki/reference/commands'
    | '/giveaways/summaries/'
    | '/wiki/advanced/'
    | '/wiki/developer/'
    | '/wiki/getting-started/'
    | '/wiki/reference/'
    | '/wiki/user-guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddedRoute: typeof AddedRoute
  InviteRoute: typeof InviteRoute
  LegalRoute: typeof LegalRouteWithChildren
  PremiumRoute: typeof PremiumRoute
  WikiRoute: typeof WikiRouteWithChildren
  ApiReportingRoute: typeof ApiReportingRoute
  AuthErrorRoute: typeof AuthErrorRoute
  GiveawaysGuildIdRoute: typeof GiveawaysGuildIdRoute
  GiveawaysOverviewRoute: typeof GiveawaysOverviewRoute
  GiveawaysIndexRoute: typeof GiveawaysIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  GiveawaysDetailsGiveawayIdRoute: typeof GiveawaysDetailsGiveawayIdRoute
  GiveawaysSummariesSummaryIdRoute: typeof GiveawaysSummariesSummaryIdRoute
  GiveawaysSummariesIndexRoute: typeof GiveawaysSummariesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/added': {
      id: '/added'
      path: '/added'
      fullPath: '/added'
      preLoaderRoute: typeof AddedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof WikiRoute
    }
    '/legal/': {
      id: '/legal/'
      path: '/'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof LegalRoute
    }
    '/giveaways/': {
      id: '/giveaways/'
      path: '/giveaways'
      fullPath: '/giveaways'
      preLoaderRoute: typeof GiveawaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/paid-services': {
      id: '/legal/paid-services'
      path: '/paid-services'
      fullPath: '/legal/paid-services'
      preLoaderRoute: typeof LegalPaidServicesRouteImport
      parentRoute: typeof LegalRoute
    }
    '/giveaways/overview': {
      id: '/giveaways/overview'
      path: '/giveaways/overview'
      fullPath: '/giveaways/overview'
      preLoaderRoute: typeof GiveawaysOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giveaways/$guildId': {
      id: '/giveaways/$guildId'
      path: '/giveaways/$guildId'
      fullPath: '/giveaways/$guildId'
      preLoaderRoute: typeof GiveawaysGuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reporting': {
      id: '/api/reporting'
      path: '/api/reporting'
      fullPath: '/api/reporting'
      preLoaderRoute: typeof ApiReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/user-guides/': {
      id: '/wiki/user-guides/'
      path: '/user-guides'
      fullPath: '/wiki/user-guides'
      preLoaderRoute: typeof WikiUserGuidesIndexRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/reference/': {
      id: '/wiki/reference/'
      path: '/reference'
      fullPath: '/wiki/reference'
      preLoaderRoute: typeof WikiReferenceIndexRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/getting-started/': {
      id: '/wiki/getting-started/'
      path: '/getting-started'
      fullPath: '/wiki/getting-started'
      preLoaderRoute: typeof WikiGettingStartedIndexRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/developer/': {
      id: '/wiki/developer/'
      path: '/developer'
      fullPath: '/wiki/developer'
      preLoaderRoute: typeof WikiDeveloperIndexRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/advanced/': {
      id: '/wiki/advanced/'
      path: '/advanced'
      fullPath: '/wiki/advanced'
      preLoaderRoute: typeof WikiAdvancedIndexRouteImport
      parentRoute: typeof WikiRoute
    }
    '/giveaways/summaries/': {
      id: '/giveaways/summaries/'
      path: '/giveaways/summaries'
      fullPath: '/giveaways/summaries'
      preLoaderRoute: typeof GiveawaysSummariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/reference/commands': {
      id: '/wiki/reference/commands'
      path: '/reference/commands'
      fullPath: '/wiki/reference/commands'
      preLoaderRoute: typeof WikiReferenceCommandsRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/getting-started/quick-start': {
      id: '/wiki/getting-started/quick-start'
      path: '/getting-started/quick-start'
      fullPath: '/wiki/getting-started/quick-start'
      preLoaderRoute: typeof WikiGettingStartedQuickStartRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/developer/markdown-test': {
      id: '/wiki/developer/markdown-test'
      path: '/developer/markdown-test'
      fullPath: '/wiki/developer/markdown-test'
      preLoaderRoute: typeof WikiDeveloperMarkdownTestRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/developer/components': {
      id: '/wiki/developer/components'
      path: '/developer/components'
      fullPath: '/wiki/developer/components'
      preLoaderRoute: typeof WikiDeveloperComponentsRouteImport
      parentRoute: typeof WikiRoute
    }
    '/giveaways/summaries/$summaryId': {
      id: '/giveaways/summaries/$summaryId'
      path: '/giveaways/summaries/$summaryId'
      fullPath: '/giveaways/summaries/$summaryId'
      preLoaderRoute: typeof GiveawaysSummariesSummaryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giveaways/details/$giveawayId': {
      id: '/giveaways/details/$giveawayId'
      path: '/giveaways/details/$giveawayId'
      fullPath: '/giveaways/details/$giveawayId'
      preLoaderRoute: typeof GiveawaysDetailsGiveawayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LegalRouteChildren {
  LegalPaidServicesRoute: typeof LegalPaidServicesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalPaidServicesRoute: LegalPaidServicesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  LegalIndexRoute: LegalIndexRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface WikiRouteChildren {
  WikiIndexRoute: typeof WikiIndexRoute
  WikiDeveloperComponentsRoute: typeof WikiDeveloperComponentsRoute
  WikiDeveloperMarkdownTestRoute: typeof WikiDeveloperMarkdownTestRoute
  WikiGettingStartedQuickStartRoute: typeof WikiGettingStartedQuickStartRoute
  WikiReferenceCommandsRoute: typeof WikiReferenceCommandsRoute
  WikiAdvancedIndexRoute: typeof WikiAdvancedIndexRoute
  WikiDeveloperIndexRoute: typeof WikiDeveloperIndexRoute
  WikiGettingStartedIndexRoute: typeof WikiGettingStartedIndexRoute
  WikiReferenceIndexRoute: typeof WikiReferenceIndexRoute
  WikiUserGuidesIndexRoute: typeof WikiUserGuidesIndexRoute
}

const WikiRouteChildren: WikiRouteChildren = {
  WikiIndexRoute: WikiIndexRoute,
  WikiDeveloperComponentsRoute: WikiDeveloperComponentsRoute,
  WikiDeveloperMarkdownTestRoute: WikiDeveloperMarkdownTestRoute,
  WikiGettingStartedQuickStartRoute: WikiGettingStartedQuickStartRoute,
  WikiReferenceCommandsRoute: WikiReferenceCommandsRoute,
  WikiAdvancedIndexRoute: WikiAdvancedIndexRoute,
  WikiDeveloperIndexRoute: WikiDeveloperIndexRoute,
  WikiGettingStartedIndexRoute: WikiGettingStartedIndexRoute,
  WikiReferenceIndexRoute: WikiReferenceIndexRoute,
  WikiUserGuidesIndexRoute: WikiUserGuidesIndexRoute,
}

const WikiRouteWithChildren = WikiRoute._addFileChildren(WikiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddedRoute: AddedRoute,
  InviteRoute: InviteRoute,
  LegalRoute: LegalRouteWithChildren,
  PremiumRoute: PremiumRoute,
  WikiRoute: WikiRouteWithChildren,
  ApiReportingRoute: ApiReportingRoute,
  AuthErrorRoute: AuthErrorRoute,
  GiveawaysGuildIdRoute: GiveawaysGuildIdRoute,
  GiveawaysOverviewRoute: GiveawaysOverviewRoute,
  GiveawaysIndexRoute: GiveawaysIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  GiveawaysDetailsGiveawayIdRoute: GiveawaysDetailsGiveawayIdRoute,
  GiveawaysSummariesSummaryIdRoute: GiveawaysSummariesSummaryIdRoute,
  GiveawaysSummariesIndexRoute: GiveawaysSummariesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
