/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as AddedRouteImport } from './routes/added'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as SummariesIndexRouteImport } from './routes/summaries/index'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as GuildsIndexRouteImport } from './routes/guilds/index'
import { Route as SummariesSummaryIdRouteImport } from './routes/summaries/$summaryId'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalPaidServicesRouteImport } from './routes/legal/paid-services'
import { Route as GuildsGuildIdRouteImport } from './routes/guilds/$guildId'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as ApiReportingRouteImport } from './routes/api/reporting'
import { Route as WikiUserGuidesIndexRouteImport } from './routes/wiki/user-guides/index'
import { Route as WikiReferenceIndexRouteImport } from './routes/wiki/reference/index'
import { Route as WikiGettingStartedIndexRouteImport } from './routes/wiki/getting-started/index'
import { Route as WikiDeveloperIndexRouteImport } from './routes/wiki/developer/index'
import { Route as WikiAdvancedIndexRouteImport } from './routes/wiki/advanced/index'
import { Route as GuildsGuildIdIndexRouteImport } from './routes/guilds/$guildId/index'
import { Route as WikiReferenceCommandsRouteImport } from './routes/wiki/reference/commands'
import { Route as WikiGettingStartedQuickStartRouteImport } from './routes/wiki/getting-started/quick-start'
import { Route as WikiDeveloperMarkdownTestRouteImport } from './routes/wiki/developer/markdown-test'
import { Route as WikiDeveloperComponentsRouteImport } from './routes/wiki/developer/components'
import { Route as GuildsGuildIdTemplatesRouteImport } from './routes/guilds/$guildId/templates'
import { Route as GuildsGuildIdSettingsRouteImport } from './routes/guilds/$guildId/settings'
import { Route as GuildsGuildIdCreateRouteImport } from './routes/guilds/$guildId/create'
import { Route as GuildsGuildIdAnalyticsRouteImport } from './routes/guilds/$guildId/analytics'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as GuildsGuildIdSummarySummaryIdRouteImport } from './routes/guilds/$guildId/summary/$summaryId'
import { Route as GuildsGuildIdDetailsGiveawayIdRouteImport } from './routes/guilds/$guildId/details/$giveawayId'

const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AddedRoute = AddedRouteImport.update({
  id: '/added',
  path: '/added',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WikiRoute,
} as any)
const SummariesIndexRoute = SummariesIndexRouteImport.update({
  id: '/summaries/',
  path: '/summaries/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegalRoute,
} as any)
const GuildsIndexRoute = GuildsIndexRouteImport.update({
  id: '/guilds/',
  path: '/guilds/',
  getParentRoute: () => rootRouteImport,
} as any)
const SummariesSummaryIdRoute = SummariesSummaryIdRouteImport.update({
  id: '/summaries/$summaryId',
  path: '/summaries/$summaryId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPaidServicesRoute = LegalPaidServicesRouteImport.update({
  id: '/paid-services',
  path: '/paid-services',
  getParentRoute: () => LegalRoute,
} as any)
const GuildsGuildIdRoute = GuildsGuildIdRouteImport.update({
  id: '/guilds/$guildId',
  path: '/guilds/$guildId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportingRoute = ApiReportingRouteImport.update({
  id: '/api/reporting',
  path: '/api/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiUserGuidesIndexRoute = WikiUserGuidesIndexRouteImport.update({
  id: '/user-guides/',
  path: '/user-guides/',
  getParentRoute: () => WikiRoute,
} as any)
const WikiReferenceIndexRoute = WikiReferenceIndexRouteImport.update({
  id: '/reference/',
  path: '/reference/',
  getParentRoute: () => WikiRoute,
} as any)
const WikiGettingStartedIndexRoute = WikiGettingStartedIndexRouteImport.update({
  id: '/getting-started/',
  path: '/getting-started/',
  getParentRoute: () => WikiRoute,
} as any)
const WikiDeveloperIndexRoute = WikiDeveloperIndexRouteImport.update({
  id: '/developer/',
  path: '/developer/',
  getParentRoute: () => WikiRoute,
} as any)
const WikiAdvancedIndexRoute = WikiAdvancedIndexRouteImport.update({
  id: '/advanced/',
  path: '/advanced/',
  getParentRoute: () => WikiRoute,
} as any)
const GuildsGuildIdIndexRoute = GuildsGuildIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuildsGuildIdRoute,
} as any)
const WikiReferenceCommandsRoute = WikiReferenceCommandsRouteImport.update({
  id: '/reference/commands',
  path: '/reference/commands',
  getParentRoute: () => WikiRoute,
} as any)
const WikiGettingStartedQuickStartRoute =
  WikiGettingStartedQuickStartRouteImport.update({
    id: '/getting-started/quick-start',
    path: '/getting-started/quick-start',
    getParentRoute: () => WikiRoute,
  } as any)
const WikiDeveloperMarkdownTestRoute =
  WikiDeveloperMarkdownTestRouteImport.update({
    id: '/developer/markdown-test',
    path: '/developer/markdown-test',
    getParentRoute: () => WikiRoute,
  } as any)
const WikiDeveloperComponentsRoute = WikiDeveloperComponentsRouteImport.update({
  id: '/developer/components',
  path: '/developer/components',
  getParentRoute: () => WikiRoute,
} as any)
const GuildsGuildIdTemplatesRoute = GuildsGuildIdTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => GuildsGuildIdRoute,
} as any)
const GuildsGuildIdSettingsRoute = GuildsGuildIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => GuildsGuildIdRoute,
} as any)
const GuildsGuildIdCreateRoute = GuildsGuildIdCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => GuildsGuildIdRoute,
} as any)
const GuildsGuildIdAnalyticsRoute = GuildsGuildIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => GuildsGuildIdRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildsGuildIdSummarySummaryIdRoute =
  GuildsGuildIdSummarySummaryIdRouteImport.update({
    id: '/summary/$summaryId',
    path: '/summary/$summaryId',
    getParentRoute: () => GuildsGuildIdRoute,
  } as any)
const GuildsGuildIdDetailsGiveawayIdRoute =
  GuildsGuildIdDetailsGiveawayIdRouteImport.update({
    id: '/details/$giveawayId',
    path: '/details/$giveawayId',
    getParentRoute: () => GuildsGuildIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/added': typeof AddedRoute
  '/invite': typeof InviteRoute
  '/legal': typeof LegalRouteWithChildren
  '/premium': typeof PremiumRoute
  '/wiki': typeof WikiRouteWithChildren
  '/api/reporting': typeof ApiReportingRoute
  '/auth/error': typeof AuthErrorRoute
  '/guilds/$guildId': typeof GuildsGuildIdRouteWithChildren
  '/legal/paid-services': typeof LegalPaidServicesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/summaries/$summaryId': typeof SummariesSummaryIdRoute
  '/guilds/': typeof GuildsIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/summaries/': typeof SummariesIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/guilds/$guildId/analytics': typeof GuildsGuildIdAnalyticsRoute
  '/guilds/$guildId/create': typeof GuildsGuildIdCreateRoute
  '/guilds/$guildId/settings': typeof GuildsGuildIdSettingsRoute
  '/guilds/$guildId/templates': typeof GuildsGuildIdTemplatesRoute
  '/wiki/developer/components': typeof WikiDeveloperComponentsRoute
  '/wiki/developer/markdown-test': typeof WikiDeveloperMarkdownTestRoute
  '/wiki/getting-started/quick-start': typeof WikiGettingStartedQuickStartRoute
  '/wiki/reference/commands': typeof WikiReferenceCommandsRoute
  '/guilds/$guildId/': typeof GuildsGuildIdIndexRoute
  '/wiki/advanced/': typeof WikiAdvancedIndexRoute
  '/wiki/developer/': typeof WikiDeveloperIndexRoute
  '/wiki/getting-started/': typeof WikiGettingStartedIndexRoute
  '/wiki/reference/': typeof WikiReferenceIndexRoute
  '/wiki/user-guides/': typeof WikiUserGuidesIndexRoute
  '/guilds/$guildId/details/$giveawayId': typeof GuildsGuildIdDetailsGiveawayIdRoute
  '/guilds/$guildId/summary/$summaryId': typeof GuildsGuildIdSummarySummaryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/added': typeof AddedRoute
  '/invite': typeof InviteRoute
  '/premium': typeof PremiumRoute
  '/api/reporting': typeof ApiReportingRoute
  '/auth/error': typeof AuthErrorRoute
  '/legal/paid-services': typeof LegalPaidServicesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/summaries/$summaryId': typeof SummariesSummaryIdRoute
  '/guilds': typeof GuildsIndexRoute
  '/legal': typeof LegalIndexRoute
  '/summaries': typeof SummariesIndexRoute
  '/wiki': typeof WikiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/guilds/$guildId/analytics': typeof GuildsGuildIdAnalyticsRoute
  '/guilds/$guildId/create': typeof GuildsGuildIdCreateRoute
  '/guilds/$guildId/settings': typeof GuildsGuildIdSettingsRoute
  '/guilds/$guildId/templates': typeof GuildsGuildIdTemplatesRoute
  '/wiki/developer/components': typeof WikiDeveloperComponentsRoute
  '/wiki/developer/markdown-test': typeof WikiDeveloperMarkdownTestRoute
  '/wiki/getting-started/quick-start': typeof WikiGettingStartedQuickStartRoute
  '/wiki/reference/commands': typeof WikiReferenceCommandsRoute
  '/guilds/$guildId': typeof GuildsGuildIdIndexRoute
  '/wiki/advanced': typeof WikiAdvancedIndexRoute
  '/wiki/developer': typeof WikiDeveloperIndexRoute
  '/wiki/getting-started': typeof WikiGettingStartedIndexRoute
  '/wiki/reference': typeof WikiReferenceIndexRoute
  '/wiki/user-guides': typeof WikiUserGuidesIndexRoute
  '/guilds/$guildId/details/$giveawayId': typeof GuildsGuildIdDetailsGiveawayIdRoute
  '/guilds/$guildId/summary/$summaryId': typeof GuildsGuildIdSummarySummaryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/added': typeof AddedRoute
  '/invite': typeof InviteRoute
  '/legal': typeof LegalRouteWithChildren
  '/premium': typeof PremiumRoute
  '/wiki': typeof WikiRouteWithChildren
  '/api/reporting': typeof ApiReportingRoute
  '/auth/error': typeof AuthErrorRoute
  '/guilds/$guildId': typeof GuildsGuildIdRouteWithChildren
  '/legal/paid-services': typeof LegalPaidServicesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/summaries/$summaryId': typeof SummariesSummaryIdRoute
  '/guilds/': typeof GuildsIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/summaries/': typeof SummariesIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/guilds/$guildId/analytics': typeof GuildsGuildIdAnalyticsRoute
  '/guilds/$guildId/create': typeof GuildsGuildIdCreateRoute
  '/guilds/$guildId/settings': typeof GuildsGuildIdSettingsRoute
  '/guilds/$guildId/templates': typeof GuildsGuildIdTemplatesRoute
  '/wiki/developer/components': typeof WikiDeveloperComponentsRoute
  '/wiki/developer/markdown-test': typeof WikiDeveloperMarkdownTestRoute
  '/wiki/getting-started/quick-start': typeof WikiGettingStartedQuickStartRoute
  '/wiki/reference/commands': typeof WikiReferenceCommandsRoute
  '/guilds/$guildId/': typeof GuildsGuildIdIndexRoute
  '/wiki/advanced/': typeof WikiAdvancedIndexRoute
  '/wiki/developer/': typeof WikiDeveloperIndexRoute
  '/wiki/getting-started/': typeof WikiGettingStartedIndexRoute
  '/wiki/reference/': typeof WikiReferenceIndexRoute
  '/wiki/user-guides/': typeof WikiUserGuidesIndexRoute
  '/guilds/$guildId/details/$giveawayId': typeof GuildsGuildIdDetailsGiveawayIdRoute
  '/guilds/$guildId/summary/$summaryId': typeof GuildsGuildIdSummarySummaryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/added'
    | '/invite'
    | '/legal'
    | '/premium'
    | '/wiki'
    | '/api/reporting'
    | '/auth/error'
    | '/guilds/$guildId'
    | '/legal/paid-services'
    | '/legal/privacy'
    | '/legal/terms'
    | '/summaries/$summaryId'
    | '/guilds/'
    | '/legal/'
    | '/summaries/'
    | '/wiki/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/guilds/$guildId/analytics'
    | '/guilds/$guildId/create'
    | '/guilds/$guildId/settings'
    | '/guilds/$guildId/templates'
    | '/wiki/developer/components'
    | '/wiki/developer/markdown-test'
    | '/wiki/getting-started/quick-start'
    | '/wiki/reference/commands'
    | '/guilds/$guildId/'
    | '/wiki/advanced/'
    | '/wiki/developer/'
    | '/wiki/getting-started/'
    | '/wiki/reference/'
    | '/wiki/user-guides/'
    | '/guilds/$guildId/details/$giveawayId'
    | '/guilds/$guildId/summary/$summaryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/added'
    | '/invite'
    | '/premium'
    | '/api/reporting'
    | '/auth/error'
    | '/legal/paid-services'
    | '/legal/privacy'
    | '/legal/terms'
    | '/summaries/$summaryId'
    | '/guilds'
    | '/legal'
    | '/summaries'
    | '/wiki'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/guilds/$guildId/analytics'
    | '/guilds/$guildId/create'
    | '/guilds/$guildId/settings'
    | '/guilds/$guildId/templates'
    | '/wiki/developer/components'
    | '/wiki/developer/markdown-test'
    | '/wiki/getting-started/quick-start'
    | '/wiki/reference/commands'
    | '/guilds/$guildId'
    | '/wiki/advanced'
    | '/wiki/developer'
    | '/wiki/getting-started'
    | '/wiki/reference'
    | '/wiki/user-guides'
    | '/guilds/$guildId/details/$giveawayId'
    | '/guilds/$guildId/summary/$summaryId'
  id:
    | '__root__'
    | '/'
    | '/added'
    | '/invite'
    | '/legal'
    | '/premium'
    | '/wiki'
    | '/api/reporting'
    | '/auth/error'
    | '/guilds/$guildId'
    | '/legal/paid-services'
    | '/legal/privacy'
    | '/legal/terms'
    | '/summaries/$summaryId'
    | '/guilds/'
    | '/legal/'
    | '/summaries/'
    | '/wiki/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/guilds/$guildId/analytics'
    | '/guilds/$guildId/create'
    | '/guilds/$guildId/settings'
    | '/guilds/$guildId/templates'
    | '/wiki/developer/components'
    | '/wiki/developer/markdown-test'
    | '/wiki/getting-started/quick-start'
    | '/wiki/reference/commands'
    | '/guilds/$guildId/'
    | '/wiki/advanced/'
    | '/wiki/developer/'
    | '/wiki/getting-started/'
    | '/wiki/reference/'
    | '/wiki/user-guides/'
    | '/guilds/$guildId/details/$giveawayId'
    | '/guilds/$guildId/summary/$summaryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddedRoute: typeof AddedRoute
  InviteRoute: typeof InviteRoute
  LegalRoute: typeof LegalRouteWithChildren
  PremiumRoute: typeof PremiumRoute
  WikiRoute: typeof WikiRouteWithChildren
  ApiReportingRoute: typeof ApiReportingRoute
  AuthErrorRoute: typeof AuthErrorRoute
  GuildsGuildIdRoute: typeof GuildsGuildIdRouteWithChildren
  SummariesSummaryIdRoute: typeof SummariesSummaryIdRoute
  GuildsIndexRoute: typeof GuildsIndexRoute
  SummariesIndexRoute: typeof SummariesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/added': {
      id: '/added'
      path: '/added'
      fullPath: '/added'
      preLoaderRoute: typeof AddedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof WikiRoute
    }
    '/summaries/': {
      id: '/summaries/'
      path: '/summaries'
      fullPath: '/summaries/'
      preLoaderRoute: typeof SummariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof LegalRoute
    }
    '/guilds/': {
      id: '/guilds/'
      path: '/guilds'
      fullPath: '/guilds/'
      preLoaderRoute: typeof GuildsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summaries/$summaryId': {
      id: '/summaries/$summaryId'
      path: '/summaries/$summaryId'
      fullPath: '/summaries/$summaryId'
      preLoaderRoute: typeof SummariesSummaryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/paid-services': {
      id: '/legal/paid-services'
      path: '/paid-services'
      fullPath: '/legal/paid-services'
      preLoaderRoute: typeof LegalPaidServicesRouteImport
      parentRoute: typeof LegalRoute
    }
    '/guilds/$guildId': {
      id: '/guilds/$guildId'
      path: '/guilds/$guildId'
      fullPath: '/guilds/$guildId'
      preLoaderRoute: typeof GuildsGuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reporting': {
      id: '/api/reporting'
      path: '/api/reporting'
      fullPath: '/api/reporting'
      preLoaderRoute: typeof ApiReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/user-guides/': {
      id: '/wiki/user-guides/'
      path: '/user-guides'
      fullPath: '/wiki/user-guides/'
      preLoaderRoute: typeof WikiUserGuidesIndexRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/reference/': {
      id: '/wiki/reference/'
      path: '/reference'
      fullPath: '/wiki/reference/'
      preLoaderRoute: typeof WikiReferenceIndexRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/getting-started/': {
      id: '/wiki/getting-started/'
      path: '/getting-started'
      fullPath: '/wiki/getting-started/'
      preLoaderRoute: typeof WikiGettingStartedIndexRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/developer/': {
      id: '/wiki/developer/'
      path: '/developer'
      fullPath: '/wiki/developer/'
      preLoaderRoute: typeof WikiDeveloperIndexRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/advanced/': {
      id: '/wiki/advanced/'
      path: '/advanced'
      fullPath: '/wiki/advanced/'
      preLoaderRoute: typeof WikiAdvancedIndexRouteImport
      parentRoute: typeof WikiRoute
    }
    '/guilds/$guildId/': {
      id: '/guilds/$guildId/'
      path: '/'
      fullPath: '/guilds/$guildId/'
      preLoaderRoute: typeof GuildsGuildIdIndexRouteImport
      parentRoute: typeof GuildsGuildIdRoute
    }
    '/wiki/reference/commands': {
      id: '/wiki/reference/commands'
      path: '/reference/commands'
      fullPath: '/wiki/reference/commands'
      preLoaderRoute: typeof WikiReferenceCommandsRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/getting-started/quick-start': {
      id: '/wiki/getting-started/quick-start'
      path: '/getting-started/quick-start'
      fullPath: '/wiki/getting-started/quick-start'
      preLoaderRoute: typeof WikiGettingStartedQuickStartRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/developer/markdown-test': {
      id: '/wiki/developer/markdown-test'
      path: '/developer/markdown-test'
      fullPath: '/wiki/developer/markdown-test'
      preLoaderRoute: typeof WikiDeveloperMarkdownTestRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/developer/components': {
      id: '/wiki/developer/components'
      path: '/developer/components'
      fullPath: '/wiki/developer/components'
      preLoaderRoute: typeof WikiDeveloperComponentsRouteImport
      parentRoute: typeof WikiRoute
    }
    '/guilds/$guildId/templates': {
      id: '/guilds/$guildId/templates'
      path: '/templates'
      fullPath: '/guilds/$guildId/templates'
      preLoaderRoute: typeof GuildsGuildIdTemplatesRouteImport
      parentRoute: typeof GuildsGuildIdRoute
    }
    '/guilds/$guildId/settings': {
      id: '/guilds/$guildId/settings'
      path: '/settings'
      fullPath: '/guilds/$guildId/settings'
      preLoaderRoute: typeof GuildsGuildIdSettingsRouteImport
      parentRoute: typeof GuildsGuildIdRoute
    }
    '/guilds/$guildId/create': {
      id: '/guilds/$guildId/create'
      path: '/create'
      fullPath: '/guilds/$guildId/create'
      preLoaderRoute: typeof GuildsGuildIdCreateRouteImport
      parentRoute: typeof GuildsGuildIdRoute
    }
    '/guilds/$guildId/analytics': {
      id: '/guilds/$guildId/analytics'
      path: '/analytics'
      fullPath: '/guilds/$guildId/analytics'
      preLoaderRoute: typeof GuildsGuildIdAnalyticsRouteImport
      parentRoute: typeof GuildsGuildIdRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guilds/$guildId/summary/$summaryId': {
      id: '/guilds/$guildId/summary/$summaryId'
      path: '/summary/$summaryId'
      fullPath: '/guilds/$guildId/summary/$summaryId'
      preLoaderRoute: typeof GuildsGuildIdSummarySummaryIdRouteImport
      parentRoute: typeof GuildsGuildIdRoute
    }
    '/guilds/$guildId/details/$giveawayId': {
      id: '/guilds/$guildId/details/$giveawayId'
      path: '/details/$giveawayId'
      fullPath: '/guilds/$guildId/details/$giveawayId'
      preLoaderRoute: typeof GuildsGuildIdDetailsGiveawayIdRouteImport
      parentRoute: typeof GuildsGuildIdRoute
    }
  }
}

interface LegalRouteChildren {
  LegalPaidServicesRoute: typeof LegalPaidServicesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalPaidServicesRoute: LegalPaidServicesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  LegalIndexRoute: LegalIndexRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface WikiRouteChildren {
  WikiIndexRoute: typeof WikiIndexRoute
  WikiDeveloperComponentsRoute: typeof WikiDeveloperComponentsRoute
  WikiDeveloperMarkdownTestRoute: typeof WikiDeveloperMarkdownTestRoute
  WikiGettingStartedQuickStartRoute: typeof WikiGettingStartedQuickStartRoute
  WikiReferenceCommandsRoute: typeof WikiReferenceCommandsRoute
  WikiAdvancedIndexRoute: typeof WikiAdvancedIndexRoute
  WikiDeveloperIndexRoute: typeof WikiDeveloperIndexRoute
  WikiGettingStartedIndexRoute: typeof WikiGettingStartedIndexRoute
  WikiReferenceIndexRoute: typeof WikiReferenceIndexRoute
  WikiUserGuidesIndexRoute: typeof WikiUserGuidesIndexRoute
}

const WikiRouteChildren: WikiRouteChildren = {
  WikiIndexRoute: WikiIndexRoute,
  WikiDeveloperComponentsRoute: WikiDeveloperComponentsRoute,
  WikiDeveloperMarkdownTestRoute: WikiDeveloperMarkdownTestRoute,
  WikiGettingStartedQuickStartRoute: WikiGettingStartedQuickStartRoute,
  WikiReferenceCommandsRoute: WikiReferenceCommandsRoute,
  WikiAdvancedIndexRoute: WikiAdvancedIndexRoute,
  WikiDeveloperIndexRoute: WikiDeveloperIndexRoute,
  WikiGettingStartedIndexRoute: WikiGettingStartedIndexRoute,
  WikiReferenceIndexRoute: WikiReferenceIndexRoute,
  WikiUserGuidesIndexRoute: WikiUserGuidesIndexRoute,
}

const WikiRouteWithChildren = WikiRoute._addFileChildren(WikiRouteChildren)

interface GuildsGuildIdRouteChildren {
  GuildsGuildIdAnalyticsRoute: typeof GuildsGuildIdAnalyticsRoute
  GuildsGuildIdCreateRoute: typeof GuildsGuildIdCreateRoute
  GuildsGuildIdSettingsRoute: typeof GuildsGuildIdSettingsRoute
  GuildsGuildIdTemplatesRoute: typeof GuildsGuildIdTemplatesRoute
  GuildsGuildIdIndexRoute: typeof GuildsGuildIdIndexRoute
  GuildsGuildIdDetailsGiveawayIdRoute: typeof GuildsGuildIdDetailsGiveawayIdRoute
  GuildsGuildIdSummarySummaryIdRoute: typeof GuildsGuildIdSummarySummaryIdRoute
}

const GuildsGuildIdRouteChildren: GuildsGuildIdRouteChildren = {
  GuildsGuildIdAnalyticsRoute: GuildsGuildIdAnalyticsRoute,
  GuildsGuildIdCreateRoute: GuildsGuildIdCreateRoute,
  GuildsGuildIdSettingsRoute: GuildsGuildIdSettingsRoute,
  GuildsGuildIdTemplatesRoute: GuildsGuildIdTemplatesRoute,
  GuildsGuildIdIndexRoute: GuildsGuildIdIndexRoute,
  GuildsGuildIdDetailsGiveawayIdRoute: GuildsGuildIdDetailsGiveawayIdRoute,
  GuildsGuildIdSummarySummaryIdRoute: GuildsGuildIdSummarySummaryIdRoute,
}

const GuildsGuildIdRouteWithChildren = GuildsGuildIdRoute._addFileChildren(
  GuildsGuildIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddedRoute: AddedRoute,
  InviteRoute: InviteRoute,
  LegalRoute: LegalRouteWithChildren,
  PremiumRoute: PremiumRoute,
  WikiRoute: WikiRouteWithChildren,
  ApiReportingRoute: ApiReportingRoute,
  AuthErrorRoute: AuthErrorRoute,
  GuildsGuildIdRoute: GuildsGuildIdRouteWithChildren,
  SummariesSummaryIdRoute: SummariesSummaryIdRoute,
  GuildsIndexRoute: GuildsIndexRoute,
  SummariesIndexRoute: SummariesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
