#!/bin/bash
set -e

APP="${1:-web}"
CHECK_TYPE="${2:-all}"
GITHUB_TOKEN="${3}"
PR_NUMBER="${4}"
REPO="${5}"

{
  echo "# 📊 Performance Analysis Report"
  echo
  echo "*Analysis for app: \`$APP\` | Check type: \`$CHECK_TYPE\`*"
  echo
  
  [[ -f bundle-comment.md ]] && cat bundle-comment.md && echo
  [[ -f lighthouse-comment.md ]] && cat lighthouse-comment.md && echo
  
  echo "---"
  echo "*This comment was automatically generated by the performance-check action.*"
} > performance-report.md

# Post comment
if command -v gh >/dev/null; then
  gh pr comment "$PR_NUMBER" --body-file performance-report.md
else
  comment_body=$(jq -Rs . performance-report.md)
  curl -s -X POST \
    -H "Authorization: Bearer $GITHUB_TOKEN" \
    -H "Accept: application/vnd.github.v3+json" \
    "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments" \
    -d "{\"body\": $comment_body}"
fi 