# --- Defaults --- #

name = "frugal-core-dev"
main = "src/index.ts"
compatibility_date = "2024-04-05"
workers_dev = true
# no_bundle = true

compatibility_flags = ["nodejs_als"]

[[d1_databases]]
binding = "D1"
database_name = "frugal"
database_id = "ddc7d747-ada2-4e1c-9946-62856277f9a1"
preview_database_id = "ddc7d747-ada2-4e1c-9946-62856277f9a1"
migrations_dir = "../../packages/d1-database/migrations"

[[kv_namespaces]]
binding = "KV"
id = "dad8c886278d4341aed8926d38747ea4"
preview_id = "dad8c886278d4341aed8926d38747ea4"

# --- Production --- #

[env.production]
name = "frugal-core-prod"

[[env.production.d1_databases]]
binding = "D1"
database_name = "frugal"
database_id = "a09d43b8-850e-4f4d-ba91-fe47d3be0ec9"
migrations_dir = "../../packages/d1-database/migrations"

[[env.production.kv_namespaces]]
binding = "KV"
id = "dad8c886278d4341aed8926d38747ea4"

# --- Staging --- #

[env.staging]
name = "frugal-core-stg"

[[env.staging.d1_databases]]
binding = "D1"
database_name = "frugal"
database_id = "b3f0981c-e213-4b28-be7f-1ba9ad731024"
migrations_dir = "../../packages/d1-database/migrations"

[[env.staging.kv_namespaces]]
binding = "KV"
id = "dad8c886278d4341aed8926d38747ea4"
