// Generated by Wrangler on Fri Oct 11 2024 14:00:10 GMT+0200 (Midden-Europese zomertijd)
// by running `wrangler types`

interface Env {
	KV_SESSIONS: KVNamespace;
	SENTRY_DSN: string;
	SESSION_SECRET: string;
	DISCORD_CLIENT_ID: string;
	DISCORD_CLIENT_SECRET: string;
	DISCORD_CALLBACK_URL: string;
	STORAGE: R2Bucket;
	D1: D1Database;
}
