on:
  workflow_dispatch:
  push:
    paths:
      - "apps/web/**"
      - ".github/workflows/cf-pages.yml"

name: Deploy to Cloudflare Pages

jobs:
  d1:
    name: Run D1 Migrations
    uses: dougley/frugal/.github/workflows/d1-migrations.yml@dev
    secrets: inherit
    with:
      environment: ${{ github.ref_name == 'main' && 'production' || 'staging' }}

  deploy:
    defaults:
      run:
        shell: bash
        working-directory: ./apps/web
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: lts
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Turbo build
        run: npx turbo build --no-cache

      - name: Build
        run: pnpm run build:mapped

      - name: Sentry Remix sourcemap upload
        run: node ./node_modules/@sentry/remix/scripts/sentry-upload-sourcemaps.js && find . -type f -name '*.map' -delete
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT_WEB }}

      - name: Publish to Cloudflare Pages
        id: cf-deploy
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: frugal
          directory: ./public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: ./apps/web
          wranglerVersion: "latest"

  sentry:
    name: Create Sentry release
    uses: dougley/frugal/.github/workflows/sentry.yml@dev
    needs: deploy
    secrets: inherit
    with:
      # if we're on main, use production, dev for staging,
      # otherwise use testing
      environment: ${{ github.ref_name == 'main' && 'production' || github.ref_name == 'dev' && 'staging' || 'testing' }}
      project: web
