name: Run D1 Migrations

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    name: Deploy
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: lts
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Migrate db
        #uses: cloudflare/wrangler-action@2.0.0
        run: npx wrangler d1 migrations apply frugal --env ${{ inputs.environment }}
        working-directory: ./apps/discord
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
