name: Create and publish Discord workers

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      skip_deploy:
        required: true
        type: string
      deploy_commands:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    name: Deploy
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Turbo build
        if: inputs.deploy_commands == 'true'
        run: pnpm turbo build --no-cache
        working-directory: ./apps/discord
        env:
          DISCORD_APP_ID: ${{ vars.DISCORD_APPLICATION_ID }}
          DISCORD_PUBLIC_KEY: ${{ vars.DISCORD_PUBLIC_KEY }}
          DISCORD_SECRET: ${{ secrets.DISCORD_SECRET }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_TOKEN }}

      - name: Deploy commands
        if: inputs.deploy_commands == 'true'
        run: pnpm run register
        working-directory: ./apps/discord
        env:
          DISCORD_APP_ID: ${{ vars.DISCORD_APP_ID }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_TOKEN }}

      - name: Publish
        # uses: cloudflare/wrangler-action@v3
        if: inputs.skip_deploy != 'true'
        run: |
          pnpm wrangler deploy --env ${{ inputs.environment }} \
            --var DISCORD_BOT_TOKEN:$DISCORD_BOT_TOKEN \
            DISCORD_APP_ID:$DISCORD_APP_ID \
            DISCORD_PUBLIC_KEY:$DISCORD_PUBLIC_KEY \
            SUMMARY_URL:$SUMMARY_SITE \
            ENVIROMENT:$ENVIROMENT \
            RELEASE:$RELEASE \
            BRANCH:$BRANCH
        working-directory: ./apps/discord
        env:
          SENTRY_DSN: ${{ vars.SENTRY_DSN_WORKERS }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT_WORKERS }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_APP_ID: ${{ vars.DISCORD_APP_ID }}
          DISCORD_PUBLIC_KEY: ${{ vars.DISCORD_PUBLIC_KEY }}
          SUMMARY_SITE: ${{ vars.SUMMARY_SITE }}
          ENVIROMENT: ${{ inputs.environment }}
          RELEASE: ${{ github.sha }}
          BRANCH: ${{ github.head_ref || github.ref_name }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
