name: Create and publish Discord workers

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      skip_deploy:
        required: false
        type: boolean
      deploy_commands:
        required: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    name: Deploy
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 18.3
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Migrate db
        if: inputs.skip_deploy != 'true'
        #uses: cloudflare/wrangler-action@2.0.0
        run: npx wrangler d1 migrations apply frugal --env staging
        working-directory: ./apps/discord
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - name: Turbo build
        if: inputs.deploy_commands == 'true'
        run: npx turbo build --no-cache
        working-directory: ./apps/discord
        env:
          DISCORD_APP_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          DISCORD_SECRET: ${{ secrets.DISCORD_SECRET }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_TOKEN }}

      - name: Deploy commands
        if: inputs.deploy_commands == 'true'
        run: pnpm run sync
        working-directory: ./apps/discord
        env:
          DISCORD_APP_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          DISCORD_SECRET: ${{ secrets.DISCORD_SECRET }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_TOKEN }}

      - name: Publish
        # uses: cloudflare/wrangler-action@2.0.0
        if: inputs.skip_deploy != 'true'
        run: npx wrangler publish --env ${{ inputs.environment }}
        working-directory: ./apps/discord
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN_WORKERS }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT_WORKERS }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_APP_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          SUMMARY_SITE: ${{ secrets.SUMMARY_SITE }}
          ENVIROMENT: ${{ inputs.environment }}
          RELEASE: ${{ github.sha }}
          BRANCH: ${{ env.GITHUB_REF_NAME }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
