name: Create and publish Discord workers

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    name: Deploy
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 18.3
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Turbo build
        run: npx turbo build --no-cache
        working-directory: ./apps/stripe

      - name: Deploy
        run: |
          npx wrangler deploy --env ${{ inputs.environment }} \
            --minify
            --var STRIPE_WEBHOOK_SECRET:$STRIPE_WEBHOOK_SECRET \
            STRIPE_SECRET_KEY:$STRIPE_SECRET_KEY \
            PREMIUM_PRODUCT_ID:$PREMIUM_PRODUCT_ID \
            PLUS_PRODUCT_ID:$PLUS_PRODUCT_ID

        working-directory: ./apps/stripe
        env:
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          PREMIUM_PRODUCT_ID: ${{ secrets.PREMIUM_PRODUCT_ID }}
          PLUS_PRODUCT_ID: ${{ secrets.PLUS_PRODUCT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
