name: Create and publish Discord workers

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    name: Deploy
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 18.3
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Turbo build
        run: npx turbo build --no-cache
        working-directory: ./apps/stripe

      - name: Sync secrets
        working-directory: ./apps/stripe
        # Wrangler accepts a JSON file with secrets for secret:bulk
        run: |
          pnpx wrangler secret:bulk update --env ${{ inputs.environment }} secrets.json

      - name: Deploy
        run: npx wrangler publish --env ${{ inputs.environment }}
        working-directory: ./apps/stripe
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
