name: Create and publish Web application

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      CF_API_TOKEN:
        required: true
      SENTRY_AUTH_TOKEN:
        required: true
      WEB_SESSION_SECRET:
        required: true
      DISCORD_SECRET:
        required: true
    outputs:
      attestation-id:
        description: "Build attestation ID"
        value: ${{ jobs.deploy.outputs.attestation-id }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    name: Deploy Web Application to ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
      attestations: write
    outputs:
      attestation-id: ${{ steps.attest-build.outputs.attestation-id }}
    steps:
      - uses: actions/checkout@v4

      - name: Build Web application
        uses: ./.github/actions/build-app
        with:
          app: web
        env:
          VITE_SENTRY_DSN: ${{ vars.SENTRY_DSN_WEB }}

      - name: Generate build attestation for Web application
        id: attest-build
        uses: ./.github/actions/build-attestation
        with:
          app: web
          subject-path: "./apps/web/build/**"

      - run: echo NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ) >> $GITHUB_ENV

      - name: Deploy to Cloudflare Pages
        uses: ./.github/actions/cloudflare-deploy
        with:
          app: web
          environment: ${{ inputs.environment }}
          api-token: ${{ secrets.CF_API_TOKEN }}
        env:
          CLOUDFLARE_ENV: ${{ inputs.environment }}
          SENTRY_DSN: ${{ vars.SENTRY_DSN_WEB }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SESSION_SECRET: ${{ secrets.WEB_SESSION_SECRET }}
          DISCORD_CLIENT_ID: ${{ vars.DISCORD_APP_ID }}
          DISCORD_PUBLIC_KEY: ${{ vars.DISCORD_PUBLIC_KEY }}
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_SECRET }}
          DISCORD_CALLBACK_URL: ${{ vars.DISCORD_CALLBACK_URL }}
          VITE_SENTRY_DSN: ${{ vars.SENTRY_DSN_WEB }}
          # Build verification variables
          ATTESTATION_ID: ${{ steps.attest-build.outputs.attestation-id }}
          BUILD_TIME: ${{ env.NOW }}
          REPOSITORY: dougley/frugal
