name: Deploy to Cloudflare Pages - Production
on: workflow_dispatch

jobs:
  deploy:
    name: Deploy Web Application
    uses: dougley/frugal/.github/workflows/web-build.yml@dev
    secrets: inherit
    with:
      environment: production

  sentry:
    name: Create Sentry release
    needs: deploy
    uses: dougley/frugal/.github/workflows/sentry.yml@dev
    secrets: inherit
    with:
      environment: production
      project: web
