name: Create and publish Web application

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    name: Deploy
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Deploy
        run: |
          pnpm wrangler deploy --env ${{ inputs.environment }} \
            --var SENTRY_DSN:$SENTRY_DSN \
            SESSION_SECRET:$SESSION_SECRET \
            DISCORD_CLIENT_ID:$DISCORD_CLIENT_ID \
            DISCORD_PUBLIC_KEY:$DISCORD_PUBLIC_KEY \
            DISCORD_CLIENT_SECRET:$DISCORD_CLIENT_SECRET \
            RELEASE:$RELEASE \
            BRANCH:$BRANCH
        working-directory: ./apps/web
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          SENTRY_DSN: ${{ vars.SENTRY_DSN_WEB }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          DISCORD_CLIENT_ID: ${{ vars.DISCORD_APP_ID }}
          DISCORD_PUBLIC_KEY: ${{ vars.DISCORD_PUBLIC_KEY }}
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_SECRET }}
          DISCORD_CALLBACK_URL: ${{ vars.DISCORD_CALLBACK_URL }}
          RELEASE: ${{ github.sha }}
          BRANCH: ${{ github.head_ref || github.ref_name }}
          VITE_SENTRY_DSN: ${{ vars.SENTRY_DSN_WEB }}
