name: Deploy to Cloudflare Workers - Production
on:
  workflow_dispatch:
    inputs:
      deploycommands:
        description: "Deploy commands?"
        required: false
        type: boolean
        default: "false"
      skipdeploy:
        description: "Skip deploy?"
        required: false
        type: boolean
        default: "false"

jobs:
  deploy:
    name: Deploy
    uses: dougley/frugal/.github/workflows/discord-build.yml@main
    secrets: inherit
    with:
      environment: production
      deploy_commands: ${{ github.event.inputs.deploycommands }}
      skip_deploy: ${{ github.event.inputs.skipdeploy }}

  sentry:
    name: Create Sentry release
    needs: deploy
    uses: dougley/frugal/.github/workflows/sentry.yml@main
    if: github.event.inputs.skipdeploy != 'true'
    secrets: inherit
    with:
      environment: production
      project: workers
