name: Deploy to Cloudflare Workers - Production
on:
  workflow_dispatch:
    inputs:
      deploycommands:
        description: 'Deploy commands?'
        required: false
        type: boolean
      skipdeploy:
        description: 'Skip deploy?'
        required: false
        type: boolean

jobs:
  deploy:
    name: Deploy
    uses: dougley/frugal/.github/workflows/discord-build.yml@main
    secrets: inherit
    with:
      environment: Production
      deploy_commands: ${{ github.event.inputs.deploycommands || 'false' }}
      skip_deploy: ${{ github.event.inputs.skipdeploy || 'false' }}
 
  sentry:
    name: Create Sentry release
    needs: deploy_worker
    uses: dougley/frugal/.github/workflows/sentry.yml@main
    if: github.event.inputs.skipdeploy != 'true'
    secrets: inherit
    with:
      environment: production
      project: workers