name: Deploy to Cloudflare Workers - Staging
on:
  workflow_dispatch:
    inputs:
      deploycommands:
        description: "Deploy commands?"
        required: false
        type: boolean
        default: "false"
      skipdeploy:
        description: "Skip deploy?"
        required: false
        type: boolean
        default: "false"
  push:
    branches:
      - main
    paths:
      - "apps/discord/**"

jobs:
  deploy:
    name: Deploy
    uses: dougley/frugal/.github/workflows/discord-build.yml@main
    secrets: inherit
    with:
      environment: staging
      deploy_commands: ${{ inputs.deploycommands }}
      skip_deploy: ${{ inputs.skipdeploy }}

  sentry:
    name: Create Sentry release
    needs: deploy
    uses: dougley/frugal/.github/workflows/sentry.yml@main
    if: github.event.inputs.skipdeploy != 'true'
    secrets: inherit
    with:
      environment: staging
      project: workers
